services:
    - docker
language: php

after_success:
    - docker login docker-registry.batandwa.me --username $DOCKER_REGISTRY_USER --password "$DOCKER_REGISTRY_PASSWORD"
    - export REPO=just-the-video/app
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO

env:
    global:
        secure: hsnXByB0CWdl08ArisKVEheGxxbMP5ixOcbsjbHl6RGJX+eifxn+XE2TtT+u/GsUCnIlzjHkBsGSvvPfkTf+Ord5+1ElUwRx3CHA5MQk6PvJc2oHLGlJ4+t5mkgOPgABgE4LmI3FxZJNfmkbUyicn/+MSWoYkqkew7da09hU7FXKzqz2ZzQyKNYKbT4PjNBsBEfqpVMGQBtu3Nq8NNgCKV1Sh7B2IrisJEcq2GYr462dPiW1cI/64xKXyV4J9Br55i5m91cdCMm07n93xmCM1spRtB644C0GB7+f+nSbD34qNQncaECrEqmrXHUxHBaBVx7nhxabL+AslPm6bH9SpOawDaLMkZKDXl38D2v9L9cbWaH49kpZWqlFmNsLrWbO8RMWiWu8fphpTxBcoPKRxtInWBwteB4OhnvpXms0gHWBl3eJyWw/HAfm0rWh5WWHP6UAKcjnLQCOpZboLm9hOS1OUdduOrXGBN0YvCNHo+FCVla/Sb4AoHy4JKIVNuhi0J3nhGFAWqMXA+HXBL3f5y7/75mB+uVsyRNdKaH55qkCM6uso8opGh3YvXcNYcuytSnXbYDTW3l7wS84XLKhx/gsXlt2JtS/i/q76FvvfxLOuHZM0iPEbgpBGG8q3L0ixOArr35IANHVDX9aAdMDC1Gqh1btmiOOwU1QRbnyVkI=
        secure: SXAoNywscc8NUEhMkF3S8Nh0nAh10f2zpUyJkyyZ9WqH9Fa71khx2XlT4bKBzTPp8AD6k4prfDWfeWEZ8HDmi23YGEepZtLg99BsSz3wSzpIgUcCe8O+ua1pAQBfnnBYQJkrm0zsPL6m28MgB9IysFIadvywMtkFHche8cpykK43THBNkYtSArQTLA8UvGQgvEd4perbI4Ul0nzIOkQy6/dyCfLp+80YFSqQfAbvzrt38s/NntXcowDPIipOIhoOlnsPs1d3qpCmdYJO1pRCW0idaXFYgk+w3qDxR7JTYx9D4Gdzt+FHEo7aM5gkGQtNyzP4P0o25ijA3X/lHO+jz0G8Ob/b7mjCxl4JWaNuMQ7PMVUdJMy+Fx5b87eKyev18QGTe/LlpPIYW0nJPum6L4je6sWHnkO+RMuOQg+ZMuXbZyRMW/phGLM6OMSXafvXLzj+VGy4gTlpMfxrLDbjePr0fIoC1ZgRZvGMBQgLYU4vOw8dBm4ntt4Yz/L2ZiGUKwD2hJNqD1MXJTA9sdZqUmGAz03SjTiN29ZIauHjgqNo0IFSdXkq5qfR8WmwncmDLQ6X5ibD24r4X4pDGwtOxj6PwpC5i5vRaguu6yfKo4RDriPEaTwDnn2zhSaiW9VbRRZNNE0JIoMLA3aVth1wv3h6/QgfJgxnA0dfs5MHBgE=

script:
    - docker login api.docker-registry.batandwa.me --username $DOCKER_REGISTRY_USER --password "$DOCKER_REGISTRY_PASSWORD"
    - docker run --rm -it -v /tmp/code:/code docker-registry.batandwa.me/node-build:latest sh -c "cd /code && yarn install"
