services:
    - docker
language: php
php:
    - 7.0
    - 7.1

after_success:
    - docker login --username $DOCKER_REGISTRY_USER --password "$DOCKER_REGISTRY_PASSWORD"
    - export REPO=api.docker-registry.batandwa.me/just-the-video/app
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO

env:
    global:
        secure: "SXAoNywscc8NUEhMkF3S8Nh0nAh10f2zpUyJkyyZ9WqH9Fa71khx2XlT4bKBzTPp8AD6k4prfDWfeWEZ8HDmi23YGEepZtLg99BsSz3wSzpIgUcCe8O+ua1pAQBfnnBYQJkrm0zsPL6m28MgB9IysFIadvywMtkFHche8cpykK43THBNkYtSArQTLA8UvGQgvEd4perbI4Ul0nzIOkQy6/dyCfLp+80YFSqQfAbvzrt38s/NntXcowDPIipOIhoOlnsPs1d3qpCmdYJO1pRCW0idaXFYgk+w3qDxR7JTYx9D4Gdzt+FHEo7aM5gkGQtNyzP4P0o25ijA3X/lHO+jz0G8Ob/b7mjCxl4JWaNuMQ7PMVUdJMy+Fx5b87eKyev18QGTe/LlpPIYW0nJPum6L4je6sWHnkO+RMuOQg+ZMuXbZyRMW/phGLM6OMSXafvXLzj+VGy4gTlpMfxrLDbjePr0fIoC1ZgRZvGMBQgLYU4vOw8dBm4ntt4Yz/L2ZiGUKwD2hJNqD1MXJTA9sdZqUmGAz03SjTiN29ZIauHjgqNo0IFSdXkq5qfR8WmwncmDLQ6X5ibD24r4X4pDGwtOxj6PwpC5i5vRaguu6yfKo4RDriPEaTwDnn2zhSaiW9VbRRZNNE0JIoMLA3aVth1wv3h6/QgfJgxnA0dfs5MHBgE="
#        secure: "Tde59jHHtmivFtVTApkVb8uESr8UPm+7Df8jktVs7XBD1rB+4VIjheSX3DBkrqEIJY6WpE1KoJaTKItwLXoqJk1KJCxoJzGhT2EWYiXEYqqk+Dwl4vHA6G6ZOQLPxQKciGoQqyJvkHtgfjsG7ZwCScOii+XjMpyOfhwuSPqzQoOxaFav4ysAHeL0rPPEydvo2kgk/3BQ7RAzwtO4UNRe7xfOowVsrd/XvDuiuOnrD8i6WtO1LUc+VxR+2bwTn1PrrKmRlbAZC8VjlfRBXx/0ECCmAkXjwWscwsiNZadr0XJfrempvGnn1IQVqkuorYwYbBoHIhE9eZzg06OpyLLeMcUuvWrQg9MW7hgEviUNV9ohUv0M8bV0Db/xliXMU9P3eiDnvXdIoSYKVvih7FRGaU5RWr2HkNlkxFHe4d6p2NMXvfOngDshWZ+oN7ZDcv3B/Y5RlSbUj9BeK9DJZlQ+/GNwc0+bhYFIOrnJP4ffkUk5B07KZmKJGaqI9GuK/lpoBCh/FQzK4Pn914Kx/B3yZxhiRqaMt98Y0zikFYpLg3+ZaHVRMmPkamFZUPH2OLWy83uXBlfEx10frNSbA2HKtbii73dXdIF4Antx0Bwza7iS30OREETd2IVuwnTBYGc+Qro0CzMcerhjIHBQoyMWID9koch3/EBoDXF/mJkU7Zw="
        secure: "RsAjaSoLun07aMi78bis1JaBpAkQE/hj9pXeazC71vlMBevEmHpHzpf1zbUcbMLrH/ux+7J9c0FYDW2ueE2TAyyOv81Vrf+nmfpsFcB1i6QmxX1aELJA7oU890oxj4rixraBPnSK9QFsswfNBkjJQetTQy/PsTIoT5W0hzlJF+Dajq35UJdAcE8JyFngxP4RYsNSh8WpfR4jX6/bbHQ0S/l9bgvZwMkwFjiYTyFOLL0bmP7K0PphCc4vRmVips+nZMMAysxhhTN69mtY2GowtoCV8z3BYcT1Th6m6Cv1ab1WiyH16SvrZJwAUWFNiV3R/1/e26l1p3uajdybYuk9AUG/UO4FHlhpnqUIypkPGRR2sO6oexmO9E3AUTh5RM4enSJHarYOLYDG1sGPbxt8bkYZKF2TCinIWyttsTvlHX99vrHnO2+5WfcclfErUsiXavCWzz6ZFKabb40Ey8yClOFI5oHyAEyvfcLW/Gfyn/kQfCtj7KK+7eXAqQGfvaQYpuk0wY8jltxoJQeC/tUos/ddCSowyENd5NBj5Box3ZhTh84He7/MKgN7auXQ/XWxWq46i+bNWK6x3G6iNYx8FlWeH77olHm2RB8MjmaAjhzKPa2ZOPh6mCrJQK+XEsHaaLSNhd2tudIfmZ2zAqmoThGttS2nVPpGEbPUyuJxFtg="

script:
#    - docker login api.docker-registry.batandwa.me --username admin --password "meccaprovepauloepsom"
#    - export DOCKER_REGISTRY_USER=admin
    - docker --version
#    - export DOCKER_REGISTRY_USER=batandwa
    - export DOCKER_REGISTRY_PASSWORD="meccaprovepauloepsom"
    - docker login api.docker-registry.batandwa.me --username $DOCKER_REGISTRY_USER --password "$DOCKER_REGISTRY_PASSWORD"
    - docker run --rm -it -v /tmp/code:/code api.docker-registry.batandwa.me/node-build:latest sh -c "cd /code && yarn install"
